### ISSUE TITLE
css font-family ease of use and clarity

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/rfcs#9]
A sore spot for quite a long time is trying to get the font-family combination correct for iOS/Android.
For a custom font such as `barlow-bold.ttf` the css needs to be:
```
font-family: Barlow, barlow-bold;
```
Getting this correct is sometimes incredibly frustrating for custom fonts.

Proposal: Potentially add a convenient cli command which prints out exactly what css is needed for any given font:

```
$ ns font /path/to/barlow-bold.ttf

Here's the CSS to use:

font-family: Barlow, barlow-bold;

Also make sure you place the font inside the `fonts` folder at root of your app.
```

Benefit: Save ton of time debugging why custom fonts aren't working.

**Comment by NathanaelA** [comment]
I fixed the RFC, android does and iOS (I believe also) use case sensitive file systems.   So if the file name is actually all lowercase "barlow-bold", and the actual internal font name is "Barlow", so it has to be cased properly; and the file linking part needs to be cased properly to lower case.  :-D 

---

Just as a forward direction; we can probably use code from:
https://www.npmjs.com/package/font-finder here to parse the OTF/TTF to get font name out of font.  (Specifically; https://github.com/princjef/font-finder/blob/master/src/parse.ts) as it parsed the TTF files to get the font into out we would need to parse.

**Comment by rigor789** [comment]
Since custom fonts are in `fonts/` folder - we could omit the file path perhaps, and just list all fonts in the folder?
```bash
$ ns fonts

Found Custom Fonts:
-------------------
barlow-bold.ttf    ->    font-family: Barlow, barlow-bold;
fontawesome.ttf    ->    font-family: FontAwesome, fontawesome;
```

Though, I guess listing system fonts could also be useful, perhaps with a flag to reduce noise?

**Comment by NathanWalker** [comment]
I like a flag to list all if desired but default would print custom fonts in fonts folder only as long as mentions that’s the output it’s printing by default clearly and mentor the flag which can be added to list all maybe / Although listing all is usually runtime related since iOS and Android only upon running can output the full list to my knowledge,
